/**
 * @your-org/observability-cli - Alertmanager configuration generator
 */

import { InstallConfig } from '../utils/prompts';

/**
 * Generate Alertmanager configuration
 */
export function generateAlertmanager(config: InstallConfig): string {
  return `# Alertmanager Configuration
# This file is auto-generated by @your-org/observability-cli

global:
  resolve_timeout: 5m
  smtp_smarthost: '${config.smtpHost}:${config.smtpPort}'
  smtp_auth_username: '${config.smtpUsername}'
  smtp_auth_password: '${config.smtpPassword}'
  smtp_from: '${config.smtpUsername}'

route:
  receiver: 'null'
  group_by:
    - alertname
    - cluster
    - service
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  routes:
    - match:
        severity: critical
        job: app
      receiver: backend-oncall
      continue: true
    
    - match:
        severity: warning
        job: app
      receiver: backend-team
      continue: false
    
    - match:
        job: infra
        severity: critical
      receiver: devops-oncall
      continue: true
    
    - match:
        job: infra
      receiver: devops-team
      continue: false
    
    - match:
        job: security
        severity: critical
      receiver: security-oncall
      continue: true
    
    - match:
        job: security
      receiver: security-team
      continue: false

receivers:
  - name: 'null'
  
  - name: 'backend-team'
    email_configs:
      - to: '${config.backendTeamEmail}'
        headers:
          Subject: '[{{ .GroupLabels.alertname }}] {{ .CommonLabels.job }} alert'
  
  - name: 'backend-oncall'
    email_configs:
      - to: '${config.oncallLeadEmail}'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .CommonLabels.job }}'
  
  - name: 'devops-team'
    email_configs:
      - to: '${config.devopsTeamEmail}'
        headers:
          Subject: '[{{ .GroupLabels.alertname }}] Infrastructure alert'
  
  - name: 'devops-oncall'
    email_configs:
      - to: '${config.oncallLeadEmail}'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - Infrastructure'
  
  - name: 'security-team'
    email_configs:
      - to: '${config.securityTeamEmail}'
        headers:
          Subject: '[{{ .GroupLabels.alertname }}] Security alert'
  
  - name: 'security-oncall'
    email_configs:
      - to: '${config.oncallLeadEmail}'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - Security'

inhibit_rules:
  - source_match:
      alertname: 'HostDown'
    target_match_re:
      alertname: '.+'
    equal:
      - 'instance'
`;
}
