/**
 * @your-org/observability-cli - OpenTelemetry configuration generator
 */

import { InstallConfig } from '../utils/prompts';

/**
 * Generate OpenTelemetry Collector configuration
 */
export function generateOtelConfig(config: InstallConfig): string {
  const receivers: string[] = ['otlp'];
  const exporters: string[] = ['prometheus', 'otlp'];

  // Add cloud-specific receivers
  if (config.cloudsInUse.includes('AWS')) {
    receivers.push('awsxray');
    receivers.push('awscontainerinsightsprometheus');
  }
  if (config.cloudsInUse.includes('Azure')) {
    receivers.push('azuremonitor');
  }
  if (config.cloudsInUse.includes('GCP')) {
    receivers.push('googlecloud');
  }

  const receiversConfig = buildReceiversConfig(receivers);
  const exportersConfig = buildExportersConfig(exporters);

  return `# OpenTelemetry Collector Configuration
# This file is auto-generated by @your-org/observability-cli

receivers:
${receiversConfig}

exporters:
${exportersConfig}

processors:
  batch:
    send_batch_size: 1024
    timeout: 10s
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
  attributes:
    actions:
      - key: environment
        value: '${config.environmentName}'
        action: upsert

service:
  pipelines:
    traces:
      receivers: [${receivers.map(r => r.replace(/_/g, '-')).join(', ')}]
      processors: [memory_limiter, batch, attributes]
      exporters: [prometheus, otlp]
    metrics:
      receivers: [${receivers.map(r => r.replace(/_/g, '-')).join(', ')}]
      processors: [memory_limiter, batch, attributes]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [otlp]
`;
}

function buildReceiversConfig(receivers: string[]): string {
  let config = '  otlp:\n    protocols:\n      grpc:\n        endpoint: "0.0.0.0:4317"\n      http:\n        endpoint: "0.0.0.0:4318"';

  if (receivers.includes('prometheus')) {
    config += '\n  prometheus:\n    config:\n      scrape_configs:\n        - job_name: "otel-collector"';
  }

  if (receivers.includes('awsxray')) {
    config += '\n  awsxray:\n    endpoint: "0.0.0.0:2000"';
  }

  if (receivers.includes('awscontainerinsightsprometheus')) {
    config += '\n  awscontainerinsightsprometheus:\n    collection_interval: 60s';
  }

  if (receivers.includes('azuremonitor')) {
    config += '\n  azuremonitor:\n    subscription_id: "your-subscription-id"';
  }

  if (receivers.includes('googlecloud')) {
    config += '\n  googlecloud:\n    project: "your-gcp-project"';
  }

  return config;
}

function buildExportersConfig(exporters: string[]): string {
  let config = '  prometheus:\n    endpoint: "0.0.0.0:8888"';

  if (exporters.includes('otlp')) {
    config += '\n  otlp:\n    endpoint: "loki:4317"';
  }

  return config;
}
