/**
 * @your-org/observability-cli - Prometheus configuration generator
 */

/**
 * Generate Prometheus configuration
 */
export function generatePrometheusConfig(): string {
  return `# Prometheus Configuration
# This file is auto-generated by @your-org/observability-cli

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'observability-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - 'app-alerts.yml'
  - 'infra-alerts.yml'
  - 'security-alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
`;
}

/**
 * Generate application alert rules
 */
export function generateAppAlerts(): string {
  return `# Application Alert Rules
# This file is auto-generated by @your-org/observability-cli

groups:
  - name: app_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: |
          sum(rate({level="error"} [5m])) by (service) > 0.1
        for: 5m
        labels:
          severity: critical
          job: app
        annotations:
          summary: "High error rate detected in {{ $labels.service }}"
          description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.service }}"

      - alert: SlowAPIResponse
        expr: |
          histogram_quantile(0.95, sum(rate({duration_ms!=""}[5m])) by (route, le)) > 1000
        for: 5m
        labels:
          severity: warning
          job: app
        annotations:
          summary: "Slow API response for {{ $labels.route }}"
          description: "95th percentile latency is {{ $value }}ms"

      - alert: ServiceDown
        expr: |
          up{job="app"} == 0
        for: 1m
        labels:
          severity: critical
          job: app
        annotations:
          summary: "Service {{ $labels.service }} is down"
          description: "Service has been down for more than 1 minute"

      - alert: HighRequestVolume
        expr: |
          sum(rate({msg!=""}[5m])) by (service) > 1000
        for: 10m
        labels:
          severity: warning
          job: app
        annotations:
          summary: "High request volume for {{ $labels.service }}"
          description: "Request rate is {{ $value }} requests/sec"
`;
}

/**
 * Generate infrastructure alert rules
 */
export function generateInfraAlerts(): string {
  return `# Infrastructure Alert Rules
# This file is auto-generated by @your-org/observability-cli

groups:
  - name: infra_alerts
    interval: 30s
    rules:
      - alert: HighCPU
        expr: |
          node_cpu_seconds_total > 0.8
        for: 5m
        labels:
          severity: warning
          job: infra
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value | humanizePercentage }}"

      - alert: HighMemory
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
          job: infra
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: DiskAlmostFull
        expr: |
          (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) > 0.9
        for: 5m
        labels:
          severity: critical
          job: infra
        annotations:
          summary: "Disk almost full on {{ $labels.instance }}"
          description: "Disk usage is {{ $value | humanizePercentage }}"

      - alert: HostDown
        expr: |
          up{job="node-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          job: infra
        annotations:
          summary: "Host {{ $labels.instance }} is down"
          description: "Host has been unreachable for more than 1 minute"
`;
}

/**
 * Generate security alert rules
 */
export function generateSecurityAlerts(): string {
  return `# Security Alert Rules
# This file is auto-generated by @your-org/observability-cli

groups:
  - name: security_alerts
    interval: 30s
    rules:
      - alert: AuthFailureSpike
        expr: |
          sum(rate({level="error", msg=~".*auth.*"}[5m])) > 10
        for: 5m
        labels:
          severity: critical
          job: security
        annotations:
          summary: "Authentication failure spike detected"
          description: "Failed auth attempts: {{ $value | humanize }}/sec"

      - alert: SuspiciousIP
        expr: |
          sum(rate({status_code="401"}[5m])) by (remote_addr) > 100
        for: 5m
        labels:
          severity: warning
          job: security
        annotations:
          summary: "Suspicious activity from IP {{ $labels.remote_addr }}"
          description: "Failed requests from this IP: {{ $value | humanize }}/sec"

      - alert: JWTAnomalies
        expr: |
          sum(rate({level="error", msg=~".*JWT.*"}[5m])) > 5
        for: 5m
        labels:
          severity: warning
          job: security
        annotations:
          summary: "JWT token anomalies detected"
          description: "JWT errors: {{ $value | humanize }}/sec"
`;
}
