/**
 * @your-org/observability-cli - Promtail configuration generator
 */

/**
 * Generate Promtail configuration for Docker environments
 */
export function generatePromtailDocker(): string {
  return `# Promtail Configuration for Docker
# This file is auto-generated by @your-org/observability-cli

server:
  http_listen_port: 9080
  log_level: info

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker: {}
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container_name
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            environment: environment
            request_id: request_id
            user_id: user_id
            duration_ms: duration_ms
            status_code: status_code
            route: route
      - labels:
          level:
          service:
          environment:
          route:

  - job_name: standalone
    static_configs:
      - targets:
          - localhost
        labels:
          job: standalone
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            environment: environment
            request_id: request_id
      - labels:
          level:
          service:
          environment:
`;
}

/**
 * Generate Promtail configuration for VM (Virtual Machine) environments
 */
export function generatePromtailVM(): string {
  return `# Promtail Configuration for Virtual Machines
# This file is auto-generated by @your-org/observability-cli

server:
  http_listen_port: 9080
  log_level: info

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd
    journal:
      max_age: 24h
      labels:
        job: systemd
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            environment: environment
      - labels:
          level:
          service:
          environment:

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:514
      label_structured_data: yes
      labels:
        job: syslog
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
      - labels:
          level:

  - job_name: application_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: application
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            environment: environment
            request_id: request_id
            user_id: user_id
            duration_ms: duration_ms
            status_code: status_code
            route: route
      - labels:
          level:
          service:
          environment:
          route:
`;
}
